Test:
  name: "Test"
  class: "org.nantes.univ.archi.plugins.test.Test"
  autoRun: true
TestAfficheur:
  name: "AfficheurConsole"
  class: "org.nantes.univ.archi.plugins.testafficheur.AfficheurConsole"
#MiageSims:
#  name: "MiageSims"
#  class: "org.nantes.univ.archi.gestionEtudiants.SimsMIAGE"
#  autoRun: true
#  dependancies : []
#Monitor:
#  name: "Monitor"
#  class: "org.nantes.univ.archi.plugin.Monitor"
#  autoRun: true