Test:
  name: "Test"
  class: "org.nantes.univ.archi.plugins.test.Test"
  autoRun: true
TestAfficheur:
  name: "AfficheurConsole"
  class: "org.nantes.univ.archi.plugins.testafficheur.AfficheurConsole"
MiageSims:
  name: "MiageSims"
  class: "org.nantes.univ.archi.plugins.gestionEtudiants.moteurMiageSims.SimsMIAGE"
  autoRun: true
InterfaceGraphiqueMiageSims:
  name: "InterfaceGraphiqueMiageSims"
  class: "org.nantes.univ.archi.plugins.gestionEtudiants.interfaceGraphique.InterfaceGraphique"
StubMiageSims:
  name: "StubMiageSims"
  class: "org.nantes.univ.archi.plugins.gestionEtudiants.stubMiageSims.StubEtudiant"
calculBonheur:
  name: "calculBonheur"
  class: "org.nantes.univ.archi.plugins.calculBonheur.CalculBonheur"
  nomBouton: "Calcul du bonheur"
determinerFuturMetier:
  name: "determinerFuturMetier"
  class: "org.nantes.univ.archi.plugins.determinerFuturMetier.DeterminerFuturMetier"
  nomBouton: "Déterminer le futur métier"
#Monitor:
#  name: "Monitor"
#  class: "org.nantes.univ.archi.plugin.Monitor"
#  autoRun: true